name: Bug report
description: Report a problem or unexpected behavior.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this! Please fill out as much as you can.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: Tell us what you observed.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: Tell us what you expected instead.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Numbered steps work best.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App/version
      description: The version/tag/commit you are using.
      placeholder: "e.g. v1.2.3 or commit hash"
    validations:
      required: false

  - type: dropdown
    id: interface
    attributes:
      label: Interface
      options:
        - CLI
        - GUI
        - Python API
        - Not sure
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - Linux
        - macOS
        - Other
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / traceback
      description: Paste relevant output here. (You can redact secrets.)
      render: text
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, configs, anything else helpful.
    validations:
      required: false
